/* Number Of Commands */
#define NOC 56

char *cmd_list[NOC] = {"ADMIN", "AWAY", "CNOTICE", "CPRIVMSG", "CONNECT", "DIE", "ENCAP", "ERROR", "HELP", "INFO", "INVITE", "ISON", "JOIN", "KICK", "KILL", "KNOCK", "LINKS", "LIST", "LUSERS", "MODE", "MOTD", "NAMES", "NICK", "NOTICE", "OPER", "PART", "PASS", "PING", "PONG", "PRIVMSG", "QUIT", "QUOTE", "REHASH", "RULES", "SERVER", "SERVICE", "SERVLIST", "SQUERY", "SQUIT", "SETNAME", "SILENCE", "STATS", "SUMMON", "TIME", "TOPIC", "TRACE", "USER", "USERHOST", "USERIP", "USERS", "VERSION", "WALLOPS", "WATCH", "WHO", "WHOIS", "WHOWAS"};
